# Generated by Django 5.2.6 on 2025-10-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('JSS1', 'Junior Secondary School 1'), ('JSS2', 'Junior Secondary School 2'), ('JSS3', 'Junior Secondary School 3'), ('SSS1', 'Senior Secondary School 1'), ('SSS2', 'Senior Secondary School 2'), ('SSS3', 'Senior Secondary School 3')], max_length=50, unique=True),
        ),
    ]
