# Generated by Django 5.2.6 on 2025-10-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='question_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
